<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Auth\Middleware\Authenticate as Middleware;
use Illuminate\Http\Request;

class Authenticate extends Middleware
{

    public function handle($request, Closure $next, ...$guards)
    {
        if(empty($guards)){
            $guards = [null];
        }

        foreach ($guards as $guard){
            if($this->auth->guard($guard)->check()){
                $this->auth->shouldUse($guard);
                return $next($request);
            }
        }


        if($request->is('api/*')){
            return response()->json([
                'error'=> 'The token is invalid',
                'code'=>401
            ],401);
        }
        return $this->unauthenticated($request,$guards);
        //return parent::handle($request, $next, $guards); // TODO: Change the autogenerated stub
    }

    /**
     * Get the path the user should be redirected to when they are not authenticated.
     */
    protected function redirectTo(Request $request): ?string
    {
        return $request->expectsJson() ? null : route('login');
    }
}